### ISSUE TITLE
Dropdown menus do not go away

### ISSUE THREAD

**Issue by eonsonicblue** [AnnyTerfect/chatgpt-prompt-helper#1]
So, referencing the "TYPE/Tone/Length/Dig Deeper/Dev / Creative/ Excel Pro" top bar. 

If I hover over anything, even if not selecting anything, the dropdown menu becomes permanently on screen for the remainder of the tab (aka they don't snap back up). 
Blocks over half of the chatgpt portion from being able to be read due to this problem. Let me 
![Screenshot 2023-05-11 8 50 07 AM](https://github.com/AnnyTerfect/chatgpt-prompt-helper/assets/19936523/60981966-4b68-454d-9b15-1cb4ab500768)

**Comment by AnnyTerfect** [comment]
Hello! Thank you for your support! Please confirm if the issue you raised is related to this project. I am unable to answer your questions until you provide more information.
